[package]
name = "nixpkgs-build-failure-notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
keyv = { version = "0.3.0", features = ["postgres"] }
reqwest = "0.12.24"
tokio = "1.48.0"
